### ISSUE TITLE
scalaz-deriving

### ISSUE THREAD

**Issue by fommil** [OlivierBlanvillain/two-phase-derivation#2]
I've heard that you're looking into automated `deriving` solutions for dotty. Have you looked through https://gitlab.com/fommil/scalaz-deriving/ yet? (will be a few months before it is finished, but it is already useful, and in production in several systems that are serving huge amounts of user-facing traffic)

**Comment by fommil** [comment]
@propensive .... actually worth asking you if you've seen *this* project, which I'd completely missed and it is now 2 years old.

**Comment by propensive** [comment]
@fommil No, I wasn't aware of it, though I knew @OlivierBlanvillain was working on something for Dotty...

**Comment by OlivierBlanvillain** [comment]
Hi guys, thanks for reaching out!

I did study Magnolia when it was first released but didn't look at scalaz-deriving until now. I didn't know it was so mature, I'm really happy to see new work in this area!

I found it quite interesting than several Scala people independently came up a similar idea to abstract over derivation with typeclasses:

- [shapeless.TypeClass](https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/typeclass.scala#L137)
- [CanDerive](https://github.com/OlivierBlanvillain/two-phase-derivation/blob/e96bea6f4769234c01c6b56d70b99915bb1104f6/src/main/scala/CanDerive.scala#L12) (from this repo)
- [scalaz-deriving.*](https://gitlab.com/fommil/scalaz-deriving#scalaz-deriving)

which, as far as I can tell, are all equivalent!

My current vision is that these typeclass based solutions have many nice properties but are too restrictive compared the `shapeless.Generic` / GHC.Generics approach. The main limitation comes from the fixed signature of the various methods to combine type class instances. For example, looking at the shapeless version:

```scala
trait ProductTypeClass[C[_]] {
  def product[H, T <: HList](ch: C[H], ct: C[T]): C[H :: T]
}
```

What if we need have additional `implicit ev: Something[C[H]]` constraints? The only solution that I see to do that is to fall back to `shapeless.Generic` where the typeclass derivation logic is duplicated for every derivation:

```scala
implicit def product[H, T <: HList]
  (implicit
    ch: C[H],
    ct: C[T],
    ev: Something[C[H]]
  ): C[H :: T]
```

We use these type of external constraints quite a bit in frameless, so it's a hard requirement on my side. (I'm I right saying than Magnolia also suffers from this limitation?)

While I'm at it I can also briefly talk about the data representation. The area I want to explore next it to use staging to derive type class instances that do not use any intermediate representation. So, given

```scala
case class Foo(s: String, i: Int)
```

I want to synthesize *exactly* this bytecode:

```scala
new Eq[Foo] {
  def equal(a: Foo, b: Foo): Boolean =
    a.s == b.s && a.i == b.i
}
```

The goal is to give enough expressive power to users to enable them to write such representation-free derivation, without having them to mess with low-level API à la `scala.reflect`. This is still very much work in progress, but here is the draft I've been playing around with: [staged-typeclass-derivation.scala](https://gist.github.com/OlivierBlanvillain/d653b1f0a2b4880d0c2acdb673e0da64). I think [this page](http://dotty.epfl.ch/docs/reference/principled-meta-programming.html) is the latest doc we have on ~ / ' and Expr.

Finally, I don't have strong opinions on the syntax... but `@deriving[] case class` looks really neat :)

**Comment by fommil** [comment]
I will have a chapter in my book comparing shapeless, scalaz-deriving and magnolia... I don't think I'd say they are equivalent at all :smile:  they are 3 very different approaches to the problem.

The biggest problem with shapeless and (maybe?) magnolia is best explained by Miles in https://github.com/milessabin/export-hook which was the primary motivation for scalaz-deriving.

**Comment by fommil** [comment]
roughly:

- shapeless == generic programming
- magnolia == magic macros
- scalaz-deriving == typeclass derivation via lawful typeclasses

and the `@deriving` annotation works for all approaches for semi-auto style.

**Comment by OlivierBlanvillain** [comment]
Can you provide a link to the chapter? I'm super interested!

(Note that at this point in the text I was talking about shapeless.TypeClass not shapeless.Generic)

**Comment by fommil** [comment]
`shapeless.TypeClass` doesn't really work that well... the more general approach I walkthrough in http://fommil.com/scalax15/#/ is realistically needed for most typeclasses.

The chapter is not yet written. I am finishing the current cahpter on Advanced Monads and should have the Typeclass Derivation chapter finished within a few monhts.

If you are at scalasphere this coming week, I'd be happy to do a code walkthrough... I'd already doing it for some others there.

**Comment by OlivierBlanvillain** [comment]
I'm not going to scalasphere, my next conf will be scala days eu

**Comment by fommil** [comment]
lambdaconf?

**Comment by fommil** [comment]
scalaio?

**Comment by OlivierBlanvillain** [comment]
Nothing planned at the moment, but if I'll make sure to message you if go to either

**Comment by fommil** [comment]
in the meantime I'm happy to answer any questions you have about scalaz-deriving either here or ping me on gitter

**Comment by fommil** [comment]
btw there is also a new deriving mechanism being proposed for haskell (another one!) I am currently going through it with the author

**Comment by OlivierBlanvillain** [comment]
link?

**Comment by fommil** [comment]
https://www.reddit.com/r/haskell/comments/8bt1o2/ghc_proposal_deriving_via/

**Comment by OlivierBlanvillain** [comment]
Thanks!
